from django.http import JsonResponse
from django.shortcuts import render
import random 

def index(request):
    return render(request, template_name='index.html')


def simple_api_view(request):
    response = JsonResponse({
        'data': [
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            'spam',
            "that was tiring"
        ]
    })
    return response
